title: run.dblock.org | running blog
locale: en_US
url:
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
kramdown:
  input: GFM
owner:
  name: Daniel Doubrovkine
  avatar: blog.png
  bio: "aka dB., NYC"
  email: dblock@dblock.org
  disqus-shortname:
  twitter: dblockdotorg
  facebook:
  google:
    plus:
    analytics: UA-4756101-5
    verify: o1dQjOsMqvIla4zMSdwhkmHSa-0mLMMi-v_ITY1BEhc
    ad-client:
    ad-slot:
  bing-verify:
  github: dblock
  stackoverflow:
  linkedin: dblock
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  youtube:
  soundcloud:
  strava: dblockdotorg
paginate: 30
google_custom_search:
edit_url: https://github.com/dblock/run.block.org/edit/gh-pages/
